name: bear blog server with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v3.3.2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}          
        
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install
      
    - name: Build
      run: yarn build

    - name: Copy Deploy Resource
      run: |
        mkdir dist
        cp -r ./bin ./dist
        cp -r ./prisma ./dist
        cp ./appspec.yml ./dist
        cp ./package.json ./dist
        cp -r ./.github/deploy-script ./dist

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: bear-blog-server-prod
        path: ./dist/          

      
  deploy:
    env:
      S3_BUCKET_DIR_NAME: server/production
      DEPLOYMENT_GROUP_NAME: production
    needs: build
    runs-on: ubuntu-latest 
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: bear-blog-server-prod

    - name: set env
      working-directory: ./
      run: |
        pwd
        touch .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        cat .env

    - name: 📦 Zip project files
      run: zip -r ./$GITHUB_SHA.zip .
  
    - name: 🌎 Access to AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: 🚛 Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3_BUCKET_NAME }}/${{ env.S3_BUCKET_DIR_NAME }}/$GITHUB_SHA.zip

    - name: 🚀 Deploy to EC2 with CodeDeploy
      run: aws deploy create-deployment
          --application-name bear-blog
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }}
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=${{ env.S3_BUCKET_DIR_NAME }}/$GITHUB_SHA.zip
